### ISSUE TITLE
offline deployment

### ISSUE THREAD

**Issue by kururu-abdo** [kururu-abdo/tornado#2]
how to deploy App offline on OS file using FxLauncher

?
@edvin

**Comment by kururu-abdo** [comment]
i received this error

WARNING: Error during Create Application phase
java.lang.ClassNotFoundException: com.example.demo.app.MyAppKt
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at fxlauncher.AbstractLauncher.createApplicationEnvironment(AbstractLauncher.java:170)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:152)
        at java.lang.Thread.run(Thread.java:745)



this is project configuration:
 <groupId>com.example.demo</groupId>
    <artifactId>myApp</artifactId>
    <version>kururu2.0</version>
    <name>kururufx</name>
<---mainClass--->
 <app.mainClass>com.example.demo.app.MyAppKt</app.mainClass>
<--base uri----->
<app.url>C://Users/kururu/Desktop</app.url>

**Comment by edvin** [comment]
You are supposed to target a JavaFX Application subclass, not a main method. I suspect you have other issues also, so maybe post your complete project as a zip file. Also, file issues on the fxlauncher project instead of in your own repo, so others can contribute as well.

**Comment by kururu-abdo** [comment]
im target MyAppKt main class of project 
it is tornadofx project
what is main class of tornadofx application

**Comment by kururu-abdo** [comment]
@edvin
